

<TITLE>HACKED BY Wh0 4m 1</TITLE>
<LINK REL="SHORTCUT ICON" HREF="http://burner.bonanza.com/background_masks/68099859.png?composite=true&transparent=true">
<META CONTENT='HACKED BY Wh0 4m 1' NAME='DESCRIPTION'/>
<META CONTENT='HACKED BY Wh0 4m 1' NAME='KEYWORDS'/>
<META CONTENT='HACKED BY Wh0 4m 1' NAME='ABSTRACT'/>
</HEAD>
<STYLE>
BODY{
 BACKGROUND:BLACK;
}
#CCOCOT{
 FONT-FAMILY:MONOSPACE;
 POSITION:ABSOLUTE;
 LEFT:0;
 LEFT:0;
 RIGHT:0;
 TOP:20%;
 COLOR:WHITE;
}
IMG {
 OPACITY:0.5;-WEBKIT-TRANSITION:ALL 250MS EASE;-MOZ-TRANSITION:ALL 250MS EASE;-O-TRANSITION:ALL 250MS EASE;TRANSITION:ALL 250MS EASE;
 MARGIN-TOP:-10PX;
}
IMG:HOVER{ 
 OPACITY:1
}
HR {
 WIDTH:250PX;
}
A{
 COLOR:WHITE;
 TEXT-DECORATION:NONE
}
A.HOVER{
 COLOR:WHITE;
}
</STYLE>
<LINK HREF='HTTP://FONTS.GOOGLEAPIS.COM/CSS?FAMILY=ICELAND' REL='STYLESHEET' TYPE='TEXT/CSS'>
<SCRIPT TYPE="TEXT/JAVASCRIPT">
VAR UID = '113084';
VAR WID = '226606';
</SCRIPT>
<BODY>
<CENTER>
<BR>
<BR>
<BR>
<BR>
<BR>
<CENTER><IMG SRC="http://burner.bonanza.com/background_masks/68099859.png?composite=true&transparent=true" WIDTH="400"/></CENTER>
<FONT FACE="MONOSPACE" SIZE="4" COLOR="WHITE" STYLE="COLOR: #000; TEXT-SHADOW: 0PX 1PX 7PX #000;"><FONT COLOR="WHITE"></FONT><FONT COLOR="WHITE"></FONT>
<FONT SIZE="7" FACE="SHARE TECH MONO" COLOR="red">HACKED BY Wh0 4m 1<br><FONT SIZE="7" FACE="SHARE TECH MONO" COLOR="WHITE">INDONESIA DEFACER BERDUKA :'( </FONT><BR>
<FONT SIZE="4" COLOR="RED">
DEAR INDONESIAN PEOPLE , </FONT>
<FONT SIZE="3" COLOR="WHITE"><PRE>
KETIKA GARUDA KEMBALI TERLUKA KARENA PROVOKASI MAHKLUK DURJANA..<BR>
KETIKA SEMBOYAN "BHINNEKA TUNGGAL IKA" KEMBALI TERABAIKAN KARENA AKSI OKNUM YG MENGATASNAMAKAN AGAMA...<BR>
KETIKA AYAT AYAT SUCI JADI BAHAN PERDEBATAN OLEH ORANG ORANG YANG MERASA MEMILIKI SURGA..<BR>
KETIKA PERJUANGAN PAHLAWAN KEMERDEKAAN SUDAH DILUPAKAN BEGITU SAJA OLEH MEREKA YG MERASA PALING BERJASA..<BR>
<BR>
TOLONG HENTIKAN SEMUA PERPECAHAN INI, TUAN..<BR>
NEGARAKU, BUKAN NEGARA SATU AGAMA ATAU MILIK KELOMPOK PERUSAK ADAT BUDAYA, JUGA BUKAN MILIK SATU GOLONGAN..<BR>
<BR>
#DAMAILAHINDONESIAKU ~ #JAYALAHBANGSAKU ~ #AKUCINTAINDONESIA<BR>
</FONT></BR></FONT>
<FONT SIZE="7" FACE="SHARE TECH MONO" COLOR="lime">LIHATLAH SAMPAI SEKARANG AKSI TERSEBUT BELUM USAI<br> DAN SANG PROVOKATOR HANYA DUDUK MANIS DAN HANYA MENYAKSIKAN<br> SIAPA PELAKUNYA CEPAT USUT :) <FONT SIZE="7" FACE="SHARE TECH MONO" COLOR="WHITE"><br>JANGAN KAU MENCARI MASALAH ORANG LAIN :) <br>Wh0 4m 1 :) INDONESIA KEMBALI BERJUANG :)<br><br><br>Thanks to : All Indonesian People <br>Greetz To : Java Hacktivist - 99Syndicate - Ponorogo Defacer Team - Dark Pinus Squad</FONT>
<BR/><BR>
<iframe width="2" height="1" src="https://www.youtube.com/embed/RvpkUhrTmxY?autoplay=1" frameborder="0" allowfullscreen></iframe>
</STYLE>
